<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="myfile.foo">
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>myfile.oof</LastGenOutput>
    </None>
    <None Update="myfile.oof">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>myfile.foo</DependentUpon>
    </None>
  </ItemGroup>

</Project>
