<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Class1.html">
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>Class1.lmth</LastGenOutput>
    </None>
    <None Update="Class1.lmth">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Class1.html</DependentUpon>
    </None>
    <None Update="myfile.foo">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>myfile.txt</LastGenOutput>
    </None>
    <None Update="myfile.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>myfile.foo</DependentUpon>
    </None>
  </ItemGroup>

</Project>
