<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="myfile.xyz">
      <Generator>SolutionFileGenerator</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Class1.cs">
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>Class1.xyz</LastGenOutput>
    </Compile>
    <Compile Update="Class2.cs">
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>Class2.xyz</LastGenOutput>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Class1.html">
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>Class1.txt</LastGenOutput>
      <CustomToolNamespace>myns</CustomToolNamespace>
    </None>
    <None Update="Class1.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Class1.html</DependentUpon>
    </None>
    <None Update="Class1.xyz">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Class1.cs</DependentUpon>
    </None>
    <None Update="Class2.xyz">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Class2.cs</DependentUpon>
    </None>
    <None Update="myfile.foo">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <Generator>SolutionFileGenerator</Generator>
      <LastGenOutput>myfile.txt</LastGenOutput>
    </None>
    <None Update="myfile.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>myfile.foo</DependentUpon>
    </None>
    <None Update="nogen.foo">
      <Generator>SolutionFileGenerator</Generator>
    </None>
  </ItemGroup>

</Project>
