<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>14</LangVersion>

    <!-- VSIX settings -->
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ColorDump\ColorWindow.xaml" />
    <None Remove="commands.vsct" />
    <None Remove="Themes\VsStyles.xaml" />
    <None Remove="ToolWindows\ExtensionsListToolWindow.xaml" />
    <None Remove="ToolWindows\ReflectorToolWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.9.820" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="ColorDump\ColorWindow.xaml">
      <Generator>XamlIntelliSenseFileGenerator</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Include="Themes\VsStyles.xaml">
      <Generator>XamlIntelliSenseFileGenerator</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Include="ToolWindows\ExtensionsListToolWindow.xaml">
      <Generator>XamlIntelliSenseFileGenerator</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Include="ToolWindows\ReflectorToolWindow.xaml">
      <Generator>XamlIntelliSenseFileGenerator</Generator>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SolutionExtensions.UI\SolutionExtensions.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Mono.Cecil">
      <HintPath>..\libs\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Design" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <VSCTCompile Include="commands.vsct">
		<AutoGen>True</AutoGen>
		<DesignTime>True</DesignTime>
		<DependentUpon>commands.t4</DependentUpon>
		<ResourceName>Menus.ctmenu</ResourceName>
	</VSCTCompile>
  </ItemGroup>
  <ItemGroup>
    <None Update="commands.t4">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>commands.vsct</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
